Revert "Suppress null-dereference warning temporarily"
This reverts commit f57d2ca2a3a985cc266ea1573c1766d8c395fcdf.

Reason for revert: Broke various B1/C1, B4/S4 targets:
./hardware/google/av/codec2/include/C2Param.h:992:24: error: pragma diagnostic expected 'error', 'warning', 'ignored', 'fatal', 'push', or 'pop' [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic ignore "-Wnull-dereference"
^

Change-Id: I5b4fc312b227a672f21cc63262e8b40d47aa9810